### ISSUE TITLE
jsonLogic is not defined on the play page

### ISSUE THREAD

**Issue by jackmatt2** [jwadhams/json-logic-js#102]
https://jsonlogic.com/play.html

<img width="929" alt="Screen Shot 2021-07-26 at 10 38 40 am" src="https://user-images.githubusercontent.com/6348088/126919011-1c8c615e-5f70-4292-9d79-f823b38cfd35.png">

**Comment by jwadhams** [comment]
I can't immediately reproduce that, can you tell me more about your browser, any relevant adblockers or plugins?

**Comment by jackmatt2** [comment]
Yep yor're right. Turns our it's my corporate network blocking
