### ISSUE TITLE
Inline operators to reduce repeated logic?

### ISSUE THREAD

**Issue by justinbmeyer** [jwadhams/json-logic-js#106]
> TLDR: Could inline operators be used to reduce repeated logic?

I'm working on an Open Source Jira estimator tool:  https://github.com/bitovi/jira-auto-scheduler

Since everyone's use of Jira is different, I'm using JsonLogic to enable people to encode how to calculate story points for an epic.  There's often a lot of repeat logic, so much so that I end up writing rules like:

```
{
  "if": [
    { ">": [epicStoryPoints, getAllChildrenStoryPoints] },
    { "-": [epicStoryPoints, getPendingChildrenStoryPoints]},

    { "!==": [getPendingChildrenStoryPoints,0]},
    getPendingChildrenStoryPoints,

    { "!==": [getTShirtSize,null]},
    { "-": [getTShirtSize, getPendingChildrenStoryPoints]},

    null
  ]
}
```

Then I `JSON.stringify()` this to get the output and use that to configure the app.  This output is ~15kb unminified and impossible to look at on its own.

Would it be possible to support some sort of routine?  A crude way of doing this might be a `operators` property:

```
jsonLogic.apply({
  operators: { fooPlusOne: {"+": [1, {var: "foo"}]  }, barPlusTwo: {"+": [2, {var: "bar"}]  } },
  "+": [{fooPlusOne: [""], barPlusTwo: [""]}
}, {foo: 5, bar: 10}) //-> 18
```

**Comment by jwadhams** [comment]
I think, as long as you're using the JavaScript implementation, this probably does what you need? https://jsonlogic.com/add_operation.html

That estimator tool sounds amazing, is there anywhere I can see it in action?

**Comment by justinbmeyer** [comment]
Thanks all!

It would be nice to have this part of the spec, that way it can work with other JSONLogic tooling / validators / etc.  However, I will custom roll it for now.
