### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by mathiasrw** [jwadhams/json-logic-js#11]
Would be awesome with "selecct examples" dropdown on http://jsonlogic.com/play.html so I dont have to start from scratch - but can poke around with different examples...

**Comment by jwadhams** [comment]
That's a great idea.  I'd actually intended to make a more compact form of the editor I could just embed into the other documentation pages (e.g., "Supported Operations" and "FizzBuzz" does that scratch the same itch?

**Comment by mathiasrw** [comment]
As long as I have some start code to poke around with its great...

**Comment by jwadhams** [comment]
Every sample on the Supported Operations page is now runnable and modifiable. Check it out and let me know what you think!  http://jsonlogic.com/operations.html

**Comment by mathiasrw** [comment]
I love it!

I suggest to rename from "Apply" to "Run"

The button is a bit pointing out in horisontal mode. I suggest removing it from its own column and placing it at the header of the result. Maybe at the right side?

It could also be that the "Result" text would be replaced with the "run" button - or a "See result" button
