### ISSUE TITLE
Addition function adding unwanted precision

### ISSUE THREAD

**Issue by JCpoz123** [jwadhams/json-logic-js#114]
We are encountering an issue when adding decimal values and wanted to know if this is a bug or if there is a workaround.

Ex.
This:
```
{
	"+": [
		0.233,
		0.232,
		0.233
	]
}
```
Returns this:
`0.6980000000000001`

When using this inside a comparison, the compare fails.  In the example if we compare the result above to "0.698", false is returned.
Other than creating our own custom "add" operator, is there another option?

**Comment by jwadhams** [comment]
that's a feature of the JavaScript programming language, and floats in general, try it from `node` or console in your browser.

```
0.233 + 0.232 + 0.233 // returns 0.6980000000000001
0.233 + 0.232 + 0.233 === 0.698 // returns false
```

Check out https://0.30000000000000004.com/, it's a pretty interesting resource, and by interesting I mean will make you doubt the nature of reality.

I think the only way around it would be to to pick up a new dependency like http://mikemcl.github.io/decimal.js/ and build custom versions of **all** the JsonLogic operations that you use that are Decimal aware. As you might imagine, this is not a practical requirement for most people so I'd suggest maintaining it as a fork.

**Comment by JCpoz123** [comment]
Thank you, good info.  I ended up replacing the default "+" operation with our own so it's working for our purposed now.

**Comment by sandrina-p** [comment]
@JCpoz123 is your fork open-sourced or closed? I'm facing the exact same struggle right now at my company.

@jwadhams, would be great if jsonLogic could support some type of config where you pass for example `{ decimal: 2 }` to always return decimals with max 2 decimals
