### ISSUE TITLE
Handle undefined

### ISSUE THREAD

**Issue by haarshjani** [jwadhams/json-logic-js#125]
I have code snippet which gives result false

```
const rule =  {
              "!==" : [{"var" : "question2"},0]
          }

jsonLogic.apply(rule,{."question1":1 })

```
no question2 in data

**expected behaviour**

question2 is undefined means != 0

must returns **_true_** as per rule

**behaviour now is**
returns **_false_**

looks like there is not handle for undefined.

**Comment by Sykander** [comment]
`!==` means compare and check type, so `undefined !== 0` is true.

You are thinking of `!=` which will do `undefined != 0` is false.

**Comment by Sykander** [comment]
![image](https://user-images.githubusercontent.com/26931543/222918566-48b6848b-7793-4bc6-98b8-989943c9b3e4.png)

I just tried this out and surprisingly it gives true for both `!=` and `!==`.

In base JS it seems `undefined == 0` does actually give false.

![image](https://user-images.githubusercontent.com/26931543/222918615-ca92fb2e-7450-4c0f-844b-33c0c9686681.png)

**Comment by jwadhams** [comment]
yeah most of the math and logic operators just defer to the implementing language, which means when the underlying language does something goofy like Sykander pointed out, JsonLogic just passes that foolishness along.

The one place the JsonLogic really unavoidably took a stand is defining [truthy and falsy](https://jsonlogic.com/truthy.html), but so far it hasn't seemed possible to do that for infix operators, where it would arguably have to define every combination of types and operands. 

If you ever want a solid laugh on this topic can I recommend https://www.destroyallsoftware.com/talks/wat

**Comment by haarshjani** [comment]
yes seems this has a  false positive behaviour and obviously undefined !== 2.

changed a logic solved the problem 

so closing the issue

Thanks for the response
