### ISSUE TITLE
Support friendly error messages?

### ISSUE THREAD

**Issue by sandrina-p** [jwadhams/json-logic-js#126]
Given a payload that is invalid, is it possible to return a friendly error message?

For example:

```json
{
  ">": [{ "var": "a" }, { "var": "b" }]
}
```

```json
{ "a": 1, "b": 2 }
```

Instead of returning `false`, it could return "1 is less than 2". (This error is based on [json-everything format](https://github.com/gregsdennis/json-everything/blob/287a985b8e41778070deb4caebc3b97193503151/JsonSchema/Localization/Resources.resx#L178)).

Another question is if it supports passing a custom error message?

Thanks :)

**Comment by jwadhams** [comment]
I guess you could wrap the logic in a big `if` like
```
{"if":[
    {">": [{ "var": "a" }, { "var": "b" }]},
    true,
    {"cat":[{ "var": "a" }, " is less than ", { "var": "b" }]}
]}
```

**Comment by sandrina-p** [comment]
Well, that's a way, thanks!
