### ISSUE TITLE
Is There a way to split String by space or Comma

### ISSUE THREAD

**Issue by Tejareddy94** [jwadhams/json-logic-js#133]
Is there a way to split string into sub-string by space or comma 

For example give a string   "Hi There" can it split it into   "Hi" and "There"

**Comment by jwadhams** [comment]
It's not baked in by default, but it would be straight forward to import `String.prototype.split` like

```js
jsonLogic.add_operation('split', (subject, delimiter) => subject.split(delimiter));
```

More info in the docs:
https://jsonlogic.com/add_operation.html

**Comment by Tejareddy94** [comment]
Okay thanks @jwadhams   
I was using ruby library. added split operation using ruby's lambda function 

Thank you so for the help @jwadhams. 
Closing this.
