### ISSUE TITLE
Reduce initial value doesn't get evaluated

### ISSUE THREAD

**Issue by Skipperwastaken** [jwadhams/json-logic-js#137]
Logic:
```js
{"reduce":[
    {"var":"integers"},
    {"+":[{"var":"current"}, {"var":"accumulator"}]},
    {"var":"start"}
]}
```
Data:
```js
{
"integers":[1,2,3],
"start": 10
}
```

I would expect this to return 16, instead it returns null, because the initial value isn't evaluated and can only be a primitive.
Changing the logic to 
```js
{"reduce":[
    {"var":"integers"},
    {"+":[{"var":"current"}, {"var":"accumulator"}]},
    10
]}
```
makes the expression work as expected.

**Comment by Tiglat-Pileser** [comment]
This is due to how the var-operator works within certain array-functions (see #130 ).

In your particular case there is a workaround, adding the start-variable as the first element of the array to be reduced:
{"reduce":[
    {"merge": [{"var": "start"}, {"var":"integers"}]},
    {"+":[{"var":"current"}, {"var":"accumulator"}]},
    0
]}

**Comment by Skipperwastaken** [comment]
Thanks for the workaround. I'd like to mention though that there is a difference between this issue and the ones mentioned in [#130](https://github.com/jwadhams/json-logic-js/issues/130). As you can see, the var function works correctly as the first parameter of the reduce function.
```js
scopedData = jsonLogic.apply(values[0], data);
scopedLogic = values[1];
initial = typeof values[2] !== "undefined" ? values[2] : null;
```
In the source code, you can see that the jsonLogicApply function is ran on the first argument, but not on the third one. Changing that line to `initial = typeof values[2] !== "undefined" ? jsonLogic.apply(values[2], data) : null;` would solve the problem. Which is actually what [this PR](https://github.com/jwadhams/json-logic-js/pull/118) does, it only needs merging.

**Comment by Tiglat-Pileser** [comment]
Aye, it is not exactly the same, but the general problem is; External evaluation of "var" only happens for the first argument of map, reduce, filter, etc. and its evaluation is done with restricted scope for all following instances of "var", where actually the restricted scope should only apply to the specific second argument where you want to browse your array or accumulator-object.

**Comment by Skipperwastaken** [comment]
Again, not quite correct. Evaluation for the third argument doesn't happen at all, not even with a restricted scope and it's not just var, no function works with the third argument, only primitive values.

**Comment by Tiglat-Pileser** [comment]
I see, I stand corrected then. Thanks for clarifying that to me.

**Comment by jwadhams** [comment]
Thanks, @ubik2 , I just merged your PR and tagged release [2.0.3](https://github.com/jwadhams/json-logic-js/releases/tag/2.0.3) Hopefully it'll be on NPM in a few minutes.

**Comment by jwadhams** [comment]
Ugh, I think I kind of biffed that release (I don't spend a lot of time publishing to NPM as you might have noticed) so you might want to jump all the way to 2.0.5

**Comment by jwadhams** [comment]
This is also part of the shared unit tests https://jsonlogic.com/tests.json and in the PHP library as of 1.5.1
