### ISSUE TITLE
examples don't work in "play with it"

### ISSUE THREAD

**Issue by deadlyicon** [jwadhams/json-logic-js#16]
examples like this

```js
jsonLogic.apply(
  { "var" : ["a"] }, // Rule
  { a : 1, b : 2 }   // Data
);
// 1
```

should be written like this

```js
jsonLogic.apply(
  { "var" : ["a"] }, // Rule
  { "a" : 1, "b" : 2 }   // Data
);
// 1
```

so they can be copied and pasted into the "play with it" page

**Comment by jwadhams** [comment]
That's an outstanding catch, thank you.

I just finished updating the Supported Operations page to make every example interactive, and it turned up a bunch more subtle problems (mostly lost commas and unbalanced brackets). Check it out, let me know what you think:

http://jsonlogic.com/operations.html
