### ISSUE TITLE
[Feature] Usage of custom function

### ISSUE THREAD

**Issue by Wardormeur** [jwadhams/json-logic-js#3]
Great work so far, I'm really interested in seeing where it can go.
I'm interested in formatting some test in a js format, based upon chai. Would it be possible to extend operations to expose chai's API ?
If so, every "parameter" which is not a logic itself would be used in an ordered way by chai's call 

Is this possible ?
Thanks :+1:

**Comment by jwadhams** [comment]
I'm not familiar with Chai, can you give me some pseudocode how that would work?

In this version I just *started* structuring the code toward allowing new operators in client code, could it be as simple as:

```js
//Introduce a new operator, this doesn't exist yet
jsonLogic.addOperator("chai_thing", function(a){ return chai.thing(a); });

//use the new operator
jsonLogic.apply({"chai_thing" : [ {"var":"a"} ] }, {"a":"apples"});
```

**Comment by Wardormeur** [comment]
I was more thinking of a provider as of "an object" that you could inject. That's less "object oriented" but would be easier when it comes to allow any test engine : nobody wants to have to redefine the whole test engine into a separate lib :)
This wouldn't break your structure, but just extend the available operators by still using apply

**Comment by jwadhams** [comment]
OK so maybe more like:

```js
//Pass in an instantiated Chai object, tell JsonLogic we'll be using "chai" as a command prefix
jsonLogic.delegateOperations("chai", chai);

//Use a method on the Chai object, jsonLogic will throw an exception if that method isn't executable
jsonLogic.apply({"chai.thing" : [ {"var":"a"} ] }, {"a":"apples"});
//Ends up basically calling chai.thing("apples")
```

**Comment by Wardormeur** [comment]
Hey, thanks for coming back to me
Basically, most test framework use some kind of composition of keywords to create a behavior
`var.should.have(a) 
or 
var.should.be(a)`
Your upper example is then missing the data to compare (because it's already a test framework embedded into a test framework)
So an example in this case "be" should behave like the operator "==" ` {"==" : [ { "var" : "pie.filling" }, "apple" ] }`
Maybe the easiest in this case would be to consider `jsonLogic.apply({"chai.should.be" : {"==" : [ { "var" : "pie.filling" }, "apple" ] };`
If it seems too complicated, I'll just wrap my logic in a way it matches your format, precalculating values and using normal operators, that's also fine by me

**Comment by jwadhams** [comment]
I need to write some documentation for it, but yesterday I added `jsonLogic.add_operation("name", function_or_object)` to introduce new libraries, and `{"method":[{"var":"some_object"}, "method_name", ["array","of","arguments"] ]}` to call methods on objects. It's available in version 1.0.9 and lines 88-248 of the unit tests are full of (simple) examples.

Given your example above, I expect it would work like:
```
jsonLogic.add_operation("chai", chai);
jsonLogic.apply({"chai.should.be" : {"==" : [ { "var" : "pie.filling" }, "apple" ] };
```

If you get a chance, I'd really appreciate your feedback!

**Comment by jwadhams** [comment]
Documentation is up!
http://jsonlogic.com/add_operation.html

**Comment by jwadhams** [comment]
I'm going to go ahead and close this, but ping me if there's anything more I can do to help you out!
