### ISSUE TITLE
Handling unknown variables

### ISSUE THREAD

**Issue by nasht00** [jwadhams/json-logic-js#39]
What is the current behavior if my rule includes a `var` which is not in the data set?

For example in the playground:

```
{
    "<": [{ "var": "LDLDiffPercentage" }, 0.5]
}
```

Returns `true` even without any data. I guess it has a default value of `0`?

Is there a way to make it FAIL when a variable is missing?

**Comment by jwadhams** [comment]
You could define a custom operator, like:

```js
jsonLogic.add_operation('var_or_die',function(key){
    var found = jsonLogic.apply({"var":[key,"unlikely sentinel"]}, this);
    if(found === "unlikely sentinel"){
        throw 'JsonLogic: var not found, '+key;
    }
    return found;
});
```

And use it like:
```
> jsonLogic.apply({"var_or_die":"foo"},null)
JsonLogic: var not found, foo
> jsonLogic.apply({"var_or_die":"foo"}, {})
JsonLogic: var not found, foo
> jsonLogic.apply({"var_or_die":"foo"}, {"foo":1})
1
```

Does that help? (I don't love the "unlikely" sentinel approach, but the stock `var` command never returns `undefined` and I didn't know if you wanted `null` to count as "found" or not.)

**Comment by jwadhams** [comment]
Oh, to answer your first question, if the data is not found, the `var` operation returns `null`.

This is kind of a weird compromise, but it boils down to inter-language compatibility. Some languages don't have separate null and undefined types, and all our [unit tests are shared between implementations as JSON](http://jsonlogic.com/tests.json), which also doesn't have an undefined type.

 JavaScript considers `null < 5 === true`

**Comment by nasht00** [comment]
Thanks
I can play around with that. 
Although in my case customers will be writing the rules themselves and I was hoping to catch them if they make a mistake. So asking them to add their own checks probably won't work :)

Would it be a problem to bake something like this into the product?
If the var evaluates to null or undefined then throw an error?

I could look into it myself by the way if needed, but the question is more if this would be an issue.

**Comment by jwadhams** [comment]
Another approach (and I'm not sure this is documented) would be to use the `uses_data` helper, which rounds up all the keys passed to `var` operations.  
So in this case, the customer misspelled `discounts` so execution should halt when we throw the exception.

```js
var customer_rule = {"*":[
    {"var":"total"},
    {"var":"disconts"}
]};

var provider_data = {
    total : 123,
    discounts : 0.10
};

var customer_uses_data = jsonLogic.uses_data(customer_rule);

var customer_used_missing = jsonLogic.apply({"missing":[customer_uses_data]}, provider_data);

if(customer_used_missing.length){
    throw "Customer rule has bad vars: " + customer_used_missing.join(', ');
}
var computed = jsonLogic.apply(customer_rule, provider_data);
console.log("Computed: ", computed)
```

`uses_data` is static analysis, so it can test all your then/else paths at once, but gets stupid about "variable variables" like `{"var":{"var":"something"}}` Honestly it probably needs a patch to throw an exception if the first arg to `var` is anything but a string.

**Comment by nasht00** [comment]
Awesome, it works.
You should document this `uses_data` method, it's very useful.
