### ISSUE TITLE
Compute numerical values

### ISSUE THREAD

**Issue by nasht00** [jwadhams/json-logic-js#40]
Is there a way for my rule to compute some numerical value?

For example imagine an e-commerce computing a percentage discount based on a rule.

**Comment by jwadhams** [comment]
Can you give me some more context? I've got an app that uses the heck out of JsonLogic for taxes, which I'd assume is similar. In that case the rule (stored in the database, per white-label customer) is something like:

```js
var tax = {
    "name":"Florida State Sales Tax",
    "value_rule":{"*":[
        0.06,
        {"var":"goods"}
    ]}
};

var purchase = {"goods":123.45}

var total = purchase.goods +  jsonLogic.apply(tax.value_rule, purchase);
```

(That's oversimplifying, there's usually an array of taxes and fees, and there are a bunch of subtotals and applicability that also have to be considered, but this is the gist of it.)

One of the little things I 😍  about this process is that if you need to support a fixed fee, making  `value_rule` a number just works, JsonLogic just passes through primitives that aren't rules.

**Comment by nasht00** [comment]
Thanks @jwadhams 
An example of such a computation would be if the discount depends on various factors such as age of the customer, country, gender, etc (this is completely bogus by the way, the real thing is more complicated).

So maybe if age is between 18 to 30 then you get a 10% discount, 30 to 50 you get 20%.
Plus a 10% if country is USA, etc.
Of course all of it stored in database just like you, white label.

**Comment by jwadhams** [comment]
Assuming you can define and document one big data object for them, like `transaction` below, your customer could provide a rule like `discounts` -- in this case the result of that rule is a percentage, which your calling code could use like the console.log commands to show pretty subtotals. (that also puts you in a position to error out if your customer's rule tries to give a 110% discount by mistake)

```
var jsonLogic = require('json-logic-js');

var transaction = {
    total : 100,
    customer : {
        age : 46,
        country : "US"
    }
};

var discounts = {"+":[
    {"if":[
        {"<=":[ 18, {"var":"customer.age"}, 30 ]},
        0.10,
        {"<=":[ 30, {"var":"customer.age"}, 50 ]},
        0.20,
        0
    ]},
    {"if":[
        {"==":[ {"var":"customer.country"}, "US"]},
        0.10,
        0
    ]}
]};

var discount_pct = jsonLogic.apply(discounts, transaction);

console.log("Subtotal: $", transaction.total);
var discount_amount = transaction.total*discount_pct;
console.log("Discounts: ", discount_pct, "% = $", discount_amount);

console.log("Total: $", transaction.total - discount_amount);
```

**Comment by jwadhams** [comment]
BTW, if you want to support *both* fixed discounts ($5 off purchases of $100 or more for example) and percentages, I think you'd have to make your customer include the "multiply percentages by total" in the rule themselves (that's how I actually use this).

**Comment by nasht00** [comment]
Thanks, that should be enough
