### ISSUE TITLE
[question] how to chain rules?

### ISSUE THREAD

**Issue by tuananh** [jwadhams/json-logic-js#43]
eg. I want to have a set of rules and have data running through all of them.

- rule 1: var `a` == 1 will multiply price by 2
- rule 2: var `b` == 2 will multiply price by 3

if i pass data as {a: 1, b: 2, price: 100}, price will be 600.

How can i do this with json-logic?

**Comment by ivan133** [comment]
You can implement something like set-temp

```
JSONLogic.add_operation('set_temp', function(key, value){
  if ( ! this.temp_variables){
    this.temp_variables = {}; 
  }
  this.temp_variables[key] = value;
  console.log('temp value', value);
  return value;
});

JSONLogic.add_operation('get_temp', function(key){
  if ( ! this.temp_variables){
    this.temp_variables = {}; 
  }
  return this.temp_variables[key];
});
```

And use get_temp on the next step
