### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by adzap** [jwadhams/json-logic-js#5]
I'm not sure if you have put supported browsers anywhere. But FYI Array.map is not supported IE8.

**Comment by mjnewman** [comment]
I haven't looked at browser support at all – This is specifically for the PHP library.

**Comment by adzap** [comment]
I don’t follow you. The js lib is for the PHP?

I should reword the issue as ‘browsers supported’

-- 
Adam Meehan

On 16 August 2016 at 12:31:19 PM, Michael Newman (notifications@github.com)
wrote:

I haven't looked at browser support at all – This is specifically for the
PHP library.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jwadhams/json-logic-js/issues/5#issuecomment-239985482>,
or mute the thread

**Comment by mjnewman** [comment]
I submitted a pull request for 'json-logic-php' – Not for the Javascript library.

**Comment by adzap** [comment]
Still not following. How does that relate to this issue in the js library?

**Comment by jwadhams** [comment]
Aw, man. So I can see a few ways to get around this:

1. Just note in the README that IE8 (0.55% of global users at this writing http://caniuse.com/#feat=es5 ) suck and won't be supported
2. Hand write a polyfill into index.js
3. Add a gulp task that generates a [Babel polyfilled](https://babeljs.io/docs/usage/polyfill/)  version for people who need it.
4. Rewrite the code to not use maps.

I'm leaning toward option 2 -- it's fast and smart for most users and not awful for IE8 users, and we're already doing it for `Array.isArray` and `Array.unique`.  (So if authors were going to have problems with gross practices like unfiltered `for in` loops over arrays, the library already bites them.)

What do you think?

**Comment by adzap** [comment]
1. I hope it dies very soon. I have to deal with it in my client work but that is unavoidable. It remains in certain types of institutions.
2. I reckon just put it in the readme that it is IE9+ and IE8 if you add the polyfill with a link to the polyfill. As long as you are clear then it is up to the developer to choose. But if you expand the polyfills built-in I guess it might just be asset weight being doubled up somewhere in the rest of the developers setup. Always the danger. The map polyfill on [MDN](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Array/map) is rather large compared to isArray or unique.

I think it is at the stage now that library devs can just say the min version and if you want point to polyfills where applicable. Then at least when they can kill off the browser they just remove the polyfills and don't need to touch the libraries.

**Comment by jwadhams** [comment]
OK, check out the updates to the readme.  Thanks for the pointer to MDN, maybe those links will both help somebody and avoid a ticket 💃

(BTW, the rest of version 1.0.7 should be a lateral change. IE8 support didn't get better or worse, I just cleaned up some internals to make writing new operators easier.)
