### ISSUE TITLE
is nested-if valid and supported?

### ISSUE THREAD

**Issue by ShawTim** [jwadhams/json-logic-js#69]
consider the following rules:

```
{"if" : [
 {"<": [{"var":"temp"}, 0] }, "0000",
 {"if": [
   {"<": [{"var":"temp"}, 100] }, "1111",
   {">": [{"var":"temp"}, 100] }, "2222",
    "3333"
 ]}, "4444",
 "5555"
]}
```

i tried it on http://jsonlogic.com/operations.html :
![image](https://user-images.githubusercontent.com/85455/58554258-18b13180-8249-11e9-8910-b2d9158ed1ec.png)

it looks like nested-if is valid. but the result looks weird to me.
- if the inner-if block is evaluated, then it should return "1111"
- if the inner-if block is not evaluated, then it looks like the block just simply returns true and thus the result is "4444"

can you confirm the behavior?

in addition,
i think if nested-if is supported, then inner-if should be evaluated.
if the inner-if is not evaluated, then it shouldn't be a valid rule.

but anyway i just want to confirm the behavior. thanks.

**Comment by jwadhams** [comment]
I've gotta figure out a way to document this more clearly, because a coworker of mine had the same problem recently.

if can take any number of arguments. It tries to pair up if/then if/then as long as it has more than 2 remaining arguments, then if there's a remaining single arg, that's the else.

So your rule could be simplified (I think) to:

```json
{"if" : [
  {"<": [{"var":"temp"}, 0] }, "0000",
  {"<": [{"var":"temp"}, 100] }, "1111",
  {">": [{"var":"temp"}, 100] }, "2222",
  "3333"
]}
```

I think the way your rule is being evaluated is more like
```
if(temp < 100) {
   inner_result = "1111";
} else if (temp > 100) {
  inner_result = "2222";
} else {
  inner_result = "3333";
}

if( temp < 0 ) {
    return "0000";
} elseif (inner_result) { // inner result is always truthy
  return "4444";
} else {
  return "5555";
}

**Comment by ShawTim** [comment]
oh i got it. so the inner-if actually evaluated as a returned value, and then json-logic uses it as a condition.
so the **nested-if** here doesnt mean to be a nested conditional branch, but more like a function with returned value which will be passed as a condition in the upper-level-if.
although the outer-if and inner-if are both evaluated, they are not in the same logic branches.

thanks for your explanation.
