### ISSUE TITLE
Operator "Starts with" and "Ends with"

### ISSUE THREAD

**Issue by fernandobd42** [jwadhams/json-logic-js#81]
**Feature**: I would like to have an operator called `StartsWith` or `EndsWith` to apply to strings, that's a bit different from `in` .

Instead `in` I'd like to use `StartsWith` or `EndsWith` operator to match the string:

** I have this rule:**
`var rules = { "and" : [`
   `{"startsWith" : [{ "var" : "temp1" }, "banana" ]},`
   `{"endsWith" : [{ "var" : "temp2" }, "apple" ]}`
`]}`

**First example**:
`var data = { "temp1" : "ban", "temp2" : "ple"  }`
`jsonLogic.apply(rules, data)` should return `true`

**Second example**:

`var data = { "temp1" : "nana", "temp2" : "app"  }`
`jsonLogic.apply(rules, data)` should return `false`

following the documentation I found this examples: http://jsonlogic.com/add_operation.html

I would like to know how I must add the operators to work like the above examples

**Comment by ppazos** [comment]
@fernandobd42 send a PR

**Comment by fernandobd42** [comment]
Yes, follow [ http://jsonlogic.com/add_operation.html](http://jsonlogic.com/add_operation.html) and it helps me to implement my custom operators.

**Comment by fasiha** [comment]
@ppazos will you accept a PR that adds `startsWith` and `endsWith`? Or do you prefer users use `add_operation`?

> Background: I stumbled on this because we React Query Builder, which can emit JsonLogic rules, is more than happy to create rules using `startsWith` and `endsWith` which of course don't work unless the app also has added these operations. Instead of adding a note in the React Query Builder documentation, we would of course prefer to help our users out and fix this in this repo. But I do understand that JsonLogic is a multi-language library 😄 hence the question, would you accept a PR.

**Comment by ppazos** [comment]
It's @fernandobd42 call I guess
